// <auto-generated />
using System;
using GeoAPI.Geometries;
using KutyApp.Services.Environment.Bll.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KutyApp.Services.Environment.Api.Migrations
{
    [DbContext(typeof(KutyAppServiceDbContext))]
    [Migration("20190114233151_dbversion")]
    partial class dbversion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KutyApp.Services.Environment.Bll.Entities.Model.DbVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("DbVerisons");
                });

            modelBuilder.Entity("KutyApp.Services.Environment.Bll.Entities.Model.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan?>("CloseTime");

                    b.Property<int>("EnvironmentTypes");

                    b.Property<string>("ImageUrl");

                    b.Property<IPoint>("Location")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<TimeSpan?>("OpeningTime");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Pois");
                });
#pragma warning restore 612, 618
        }
    }
}
